spring:
  application:
    name: aicareercoach
  data:
    mongodb:
      uri: ${MONGODB_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:file:.env[.properties]

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-make-it-long-and-secure}
  expiration: 3600000 # 1 hour in milliseconds (reduced from 24 hours)
  refresh-expiration: 604800000 # 7 days in milliseconds
  inactivity-timeout: 1800000 # 30 minutes of inactivity

# Logging Configuration
logging:
  level:
    com.aicareercoach: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  info:
    title: AI Career Coach API
    description: Backend API for AI Career Coach platform
    version: 1.0.0
    contact:
      name: AI Career Coach Team
      email: support@aicareercoach.com

# Custom Application Properties
app:
  file:
    upload-dir: ./uploads
    max-size: 10MB
  pagination:
    default-page-size: 20
    max-page-size: 100
  roadmap:
    default-duration-weeks: 12
    max-tasks-per-day: 5
    buffer-days-percentage: 20
  task:
    default-duration-minutes: 60
    max-daily-hours: 8
    weekend-catchup-enabled: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# AI Timeline Configuration
ai:
  timeline:
    enabled: false  # Set to true to enable AI timeline features

# OpenAI API key (should be set via environment variable in production)
OPENAI_API_KEY: "" 