package com.aicareercoach.domain;

public enum JobRole {
    TECH_SUPPORT,
    SOFTWARE_DEVELOPER,
    FULL_STACK_DEVELOPER,
    FRONTEND_DEVELOPER,
    BACKEND_DEVELOPER,
    DATA_SCIENTIST,
    DEVOPS_ENGINEER,
    PRODUCT_MANAGER,
    UI_UX_DESIGNER,
    QA_ENGINEER,
    SYSTEM_ADMINISTRATOR,
    NETWORK_ENGINEER,
    SECURITY_ANALYST,
    BUSINESS_ANALYST,
    PROJECT_MANAGER,
    OTHER
} 